### ISSUE TITLE
[Goonj] in production location is not uploaded in properly 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/Goonj#38]
In the production environment for goonj  locations are missing.

Because of this  integration getting failed .

2022-09-16 05:16:02,970 ERROR [org.avni_integration_service.goonj.worker.goonj.DemandEventWorker] Goonj Demand a1CC2000000CkIPMA0 could not be synced to Goonj Salesforce.
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : "Address 'Maharashtra, Mumbai City' not found"

**Comment by himeshr** [comment]
On Investigation, we found that locations have been upated correctly in avni staging as well as production.
There are a few districts missing in the source dump provided by Goonj, due to which we had this issue.
Fix for future issues with missing Districts, is to create the district manually in Avni-webapp using admin user and admin Locations creation functionality.
