### ISSUE TITLE
[Goonj] Major UAT Feedback items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Goonj#58]
- [x] A demand which was dispatched and which is not part of the GET demands API is still being shown in the Demands folder. 
2023/ACC-195025/PNB/022
2023/ACC-195025/PNB/021
- [x] Images in SalesForce sent from Avni are linked to an S3 url, which is a problem because they are not publicly accessible. These links are being shown in SF and are throwing access errors. We decided to change the url to a form that is accessible through an Avni login.
- [x] "Total Number of Participants Other"   is missing in CFW  and  NJPC initiatives. The field in API for CFW is:- NoofparticipantsCFWOther and for NJPC is:- NoofparticipantsNJPCOther
- [x] Activity form - The start date and end date can be the same. In that case the number of days==1 is valid
- [x] S2S acttivity created  on 8th may afternoon got updated in the evening of 8th May
- [x] Activity  Conducted with Students has to be a multi select field. 
- [x] Add Other block for all existing districts used for testing, Add Other village option for all the existing Blocks as well as Other block
- [x] Allow disptach receipt date to be same as Dispatch date.
- [x] Add dashboard cards for:
- Activities linked to distribution
- Activities not linked to distribution
- Distribution without activities

**Comment by BEULAHEVANJALIN** [comment]
Things that cannot be done at the moment
- Show Tola/Mohalla field in the Activity and distribution forms immediately after the address fields so that it is linked to overall location hierarchy for visibility: They were asking us to show this Tola/Mohalla field in the first page (default non-editable page)

Things to be discussed:
-  Getting authorization error when trying to click on the photo link which is being stored in salesforce: After clicking the image url they are redirected to avni webapp but getting access error on the web page. I have appended "https://app.avniproject.org/web/media?url=" to the image url and not sure if I should add "staging.avniproject.org" instead of "app.avniproject.org". So this needs to be discussed with Vinay.

Things that are pending to be do:
- [x]  Activity Conducted with Students has to be a multi select field.
- [x]  Add Other block for all existing districts used for testing, Add Other village option for all the existing Blocks as well as Other block. 
- [ ]  And when Other block and Other village is selected in the form, show a text field to mention the other block and other village name.

**Comment by BEULAHEVANJALIN** [comment]
For the point ,
- While saving a distribution, do not allow Save if the current quantity of Inventory is 0.


I tried to console/fetch the data associated with the concept of type 'subject type' but couldn't get any result. Debugging this (in process) and should be discussed as well.

**Comment by utkarshavni** [comment]
@BEULAHEVANJALIN removed product dependent items from card and moving this to dev complete
New card link:
https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/goonj/61
